### ISSUE TITLE
How to cancel upload request?

### ISSUE THREAD

**Issue by josephbuchma** [jaydenseric/apollo-upload-client#119]
I can't find an example of upload request cancellation. Is it possible to abort file upload aside from leaving page?

**Comment by jaydenseric** [comment]
That's a good question; it's not something I have done before.

By the looks of things, [aborting pending requests is not an Apollo Client feature yet](https://github.com/apollographql/apollo-feature-requests/issues/40). HTTP terminating links seem to have some level of support for aborting the fetch requests, but never learned properly in what circumstances that would happen.

`apollo-link-http`:

https://github.com/apollographql/apollo-link/blob/ef771ac1bf49bd111062eab8833f7f90c2b9803c/packages/apollo-link-http/src/httpLink.ts#L169

`apollo-upload-client`:

https://github.com/jaydenseric/apollo-upload-client/blob/f61c49eafbf800b968d06b081abdfb45878989b2/src/index.js#L150

Keep in mind that Apollo Server uses a fork of a flawed old version of `graphql-upload`. It crashes the server when a client aborts an upload request, so if you use Apollo Server you may not want to encourage this.

**Comment by nellh** [comment]
I've done this with [XMLHttpRequest instead of fetch](https://github.com/OpenNeuroOrg/openneuro/blob/2e045875e6b06327f97df1bcdfb6ab5f9398a854/packages/openneuro-app/src/scripts/uploader/xhrfetch.js) and calling [XMLHttpRequest.abort()
 to end the upload](https://github.com/OpenNeuroOrg/openneuro/blob/2e045875e6b06327f97df1bcdfb6ab5f9398a854/packages/openneuro-app/src/scripts/uploader/uploader.jsx#L298). This is also useful for tracking upload progress.

**Comment by jaydenseric** [comment]
An update; [Apollo Server v2.3](https://github.com/apollographql/apollo-server/blob/master/CHANGELOG.md#v230) uses `graphql-upload`, allowing safe handling of aborted upload requests.

Since `apollo-upload-client`, along with most Apollo Client terminating links, uses the `fetch` API, the "correct" way to abort an upload request is to use [standard `fetch` abort signals](https://developers.google.com/web/updates/2017/09/abortable-fetch#abort_signals_and_fetch).

In theory [this is supported](https://github.com/jaydenseric/apollo-upload-client/blob/v9.1.0/src/index.js#L150), but I have not used the feature myself. If it doesn't work correctly, feel free to raise a new issue :)
