### ISSUE TITLE
How to compose wss and upload links?

### ISSUE THREAD

**Issue by olchyk98** [jaydenseric/apollo-upload-client#122]
Hi, there!

I'm trying to combine upload-link and websocketlink using apollolink.

```
import { ApolloClient } from 'apollo-boost';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { WebSocketLink } from 'apollo-link-ws';
import { createUploadLink } from 'apollo-upload-client';
import { concat } from 'apollo-link';

import { apiPath, wssPath } from './apiPath';

const client = new ApolloClient({
	link: concat(
		new WebSocketLink({
     		uri: `${ wssPath }/graphql`,
      		options: { reconnect: true }
    	}),
		createUploadLink({ uri: `${ apiPath }/graphql` })
	),
	cache: new InMemoryCache()
});

export default client;
```

but i'm receiving error from uploadlink and from apollo (You are calling concat on a terminating link, which will have no effect).

Please, help me..

**Comment by jaydenseric** [comment]
A terminating link is one that sends the actual request to the GraphQL endpoint, so logically links concatenated afterwards can't do anything to influence a request already sent.

I don't know exactly the right way to setup all those things from my head, but since this is a general Apollo usage question (and not an `apollo-upload-client` bug) you might have some luck asking in the Apollo Slack 🤞
