### ISSUE TITLE
Nodejs?

### ISSUE THREAD

**Issue by optimuspaul** [jaydenseric/apollo-upload-client#134]
The README says this supports node but I don't see any examples and another ticket pointed to some "sample" code that was a nightmare and didn't actually work for my setup. Does this actually work with Node or not?

**Comment by mike-marcacci** [comment]
Hey @optimuspaul, what exactly are you encountering? I do use this in place of Apollo's default http link on node for all our SSR needs... but I don't actually upload files from node. That said, most of the logic here is handled by [extract-files](https://github.com/jaydenseric/extract-files) which is thoroughly tested on node.

If you can describe what you're trying to do, and where you're running into trouble, somebody can probably point you in the right direction.

I assume you already have Apollo client working in node? If not, that's going to be your first thing to look at, and you might have better luck in the appropriate Apollo slack channel.

On the other hand, if the upload module is crashing or misbehaving in node, a list of steps to reproduce would be hugely appreciated here.

**Comment by optimuspaul** [comment]
I actually don't have the Apollo Client running yet, I have been using `graphql-request` so far since setting up apollo seemed like a weekend project rather than a simple config when I first looked into it. I was actually able to make it work writing my own client fairly quickly having spent the time to build a python client as well.

I think the point on this was, "where are the examples?"

**Comment by jaydenseric** [comment]
@optimuspaul your instinct to use someting lighter than Apollo to upload a file from a server is sound; I suggest using [`node-fetch`](https://npm.im/node-fetch) and [`form-data`](https://npm.im/form-data) directly, and just follow the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure). Something like this:

```js
import FormData from 'form-data'
import fetch from 'node-fetch'

async function upload(graphqlUri, stream) {
  const body = new FormData()

  body.append(
    'operations',
    JSON.stringify({
      query: /* GraphQL */ `
        mutation($file: Upload!) {
          uploadFile(file: $file) {
            success
          }
        }
      `,
      variables: {
        file: null
      }
    })
  )

  body.append('map', JSON.stringify({ 1: ['variables.file'] }))
  body.append('1', stream)

  await fetch(graphqlUri, { method: 'POST', body })
}
```

This assumes the `stream` is from `fs`, or is otherwise consumable by `form-data`; read their documentation to see how to manually set the filename, known length, etc. if it can't be determined automatically:

```js
body.append('1', stream, {
  filename: 'test.jpg',
  contentType: 'image/jpeg',
  knownLength: 19806
})
```

[`graphql-upload` tests](https://github.com/jaydenseric/graphql-upload/blob/v8.0.2/src/test.mjs#L76) use `fetch` and `FormData`. Don't study them too hard though, because they only include the minimum parts of a complete GraphQL multipart request required for each test (e.g. the operation `query` is missing in most).

There have been ideas to add support for Node.js streams to [`extract-files`](https://npm.im/extract-files) (a dependency of most GraphQL file upload clients), to help with server-side file uploads, schema stitching, etc. but no one is actively working on it at the moment.

**Comment by tidjungs** [comment]
@jaydenseric 
this solution now working when i use createReadStream with bigger file such as .jpeg
server side not completely receive all buffer of stream

**Comment by sbichenko** [comment]
Has anyone managed to actually upload a file to a GraphQL server from a NodeJS server? I haven't found a single working solution yet.
