### ISSUE TITLE
Error 400 Bad Request from server, createUploadLink apolloClient link setup

### ISSUE THREAD

**Issue by ghost** [jaydenseric/apollo-upload-client#141]
Hi my mutation format looks like this:

```
import gql from 'graphql-tag'

export default (
  apolloClient,
  file,
) => {
  apolloClient
    .mutate({
      mutation: gql`
        mutation createGroup($file: Upload!) {
          createGroup(input: {file: $file}) {
            id
          }
        }
      `,
      variables: { file }
    })
}
```

I have an issue with sending my form data through the network, my request looks like this:

<img width="1046" alt="screen shot 2019-01-27 at 1 17 25 am" src="https://user-images.githubusercontent.com/30026659/51797425-5df92000-21d1-11e9-81ec-0dd4074db07d.png">

It probably shouldn't look like that correct?

Here is how I initialize my apollo client:

```
  return new ApolloClient({
    connectToDevTools: process.browser,
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    link: ApolloLink.from([ authLink, uploadLink ]),
    cache: new InMemoryCache().restore(initialState || {})
  })
```

Where my authLink looks like this:

```
  const authLink = setContext((_, { headers }) => {
    const token = getToken()
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : ''
      }
    }
  })
```

And my uploadLink looks like this:
```
  const uploadLink = createUploadLink({
    uri: '/api/graphql',
    credentials: 'same-origin'
  })
```

Honestly not sure what is wrong, I could do my other mutations just fine

**Comment by mike-marcacci** [comment]
Hi @sc4224, that looks correct as the payload for a request containing an upload, assuming it’s multipart and also contains the file contents in another part.

Silly question perhaps, but does your server support uploads? Without support from the server, I would expect a 404.

**Comment by mike-marcacci** [comment]
Hmmm, I'll assume you're using absinthe as your graphql server (since you're using elixir). Looking at their [upload guide](https://github.com/absinthe-graphql/absinthe/blob/master/guides/file-uploads.md) it does appear that they aren't expecting an HTTP request conforming to the [GraphQL Multipart Request spec](https://github.com/jaydenseric/graphql-multipart-request-spec) but rather their own absinthe-specific format. It looks like they have [their own client-side package](https://www.npmjs.com/package/apollo-absinthe-upload-link) for generating those requests.
