### ISSUE TITLE
Support GET requests

### ISSUE THREAD

**Issue by JohannesLamberts** [jaydenseric/apollo-upload-client#151]
I am trying to use https://github.com/apollographql/apollo-link-persisted-queries in combination with apollo-upload-client.

When I set `{ useGETForHashedQueries: true }` in the options of the persisted-queries link, network requests fail:

`Network error: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`

It seems to me, that the handling of apollo-link-http (https://github.com/apollographql/apollo-link/blob/efd104055f675fae3b24be7b96b009099ac040e7/packages/apollo-link-http/src/httpLink.ts#L119) is missing in https://github.com/jaydenseric/apollo-upload-client/blob/4d0c29a2d0a663c411446980836e9c3668e204ab/src/index.js#L154.

IMHO it should be possible to add that handling in case of `!(files.size)`, but that would add the complexity of `rewriteURIForGET` from apollo-link-http to this package...

**Comment by laukaichung** [comment]
This PR by @raymondsze  https://github.com/jaydenseric/apollo-upload-client/pull/146 seems to fix the problem. But it is blocked. Hope it gets approved soon!

**Comment by jessiecrisvicerra** [comment]
Hoping it will be merge soon. Needed it for the project. If not, is there any alternative for apollo-upload-client?

**Comment by mike-marcacci** [comment]
@laukaichung @jessiecrisvicerra it looks like the build on that PR is failing; fixing that might be a good way to move it along 😉

**Comment by jessiecrisvicerra** [comment]
Heya, the errors are just prettier issues. I can fix the issue but not sure how to proceed.

**Comment by jclvicerra** [comment]
I have already fix the eslint issue PR #160 along with the PR on @raymondsze #146. Can somebody approve it? 
@jaydenseric .

**Comment by jaydenseric** [comment]
Thank you everyone for your patience 🙏

The reason the PR for this has not been a quick merge is because there are no tests, and this feature is a little bit complex.

I would need to spend a fair bit of time to thoroughly understand the problem, how the Apollo solution works, then setup some test projects to verify that our implementation here works. Ongoing TLC will be needed to ensure these features track any changes to the upstream Apollo implementation.

The design of the Apollo links is not very convenient for maintaining a package like this one that only intends to enhance a small part of how HTTP link works.

These PR's have been in limbo because I don't use Apollo Client/Server anymore these days. I've been happily using my own GraphQL stack for some time; [`graphql-api-koa`](https://github.com/jaydenseric/graphql-api-koa) for APIs (which works great with [`graphql-upload`](https://github.com/jaydenseric/graphql-upload)) and [`graphql-react`](https://github.com/jaydenseric/graphql-react) for apps (which supports file uploads out of the box).

I still maintain this package with it's current feature set and quickly fix bugs thatarisee, it's just new features that will take a while to ship.

**Comment by jaydenseric** [comment]
The best way to get this feature shipped is for someone to PR the [apollographql/apollo-link](https://github.com/apollographql/apollo-link) repo to move the [`rewriteURIForGET`](https://github.com/apollographql/apollo-link/blob/c6f0cf7f3a02bf34587c9660387ca8a4b16d4bb8/packages/apollo-link-http/src/httpLink.ts#L198) helper function in the [`apollo-link-http`](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http) package to the [`apollo-link-http-common`](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http-common) package.

That way we can import an already tested and maintained helper here to use, instead of a large copy-paste job which is risky without tests, that will be a maintenance burden over time. Also, if a project bundles both `apollo-link-http` and `apollo-upload-client` it will have a smaller bundle size due to the shared helper; other Apollo link projects that are in the same boat may also benefit.

**Comment by geiszla** [comment]
I rely on GET queries to get the CSRF token on my current setup, so I can't just replace http link with the upload link. Is there a quick workaround (like splitting the requests with `apollo-link`'s split) until the PR gets merged?

**Comment by jaydenseric** [comment]
Support for GET requests has been published in [v14.1.0](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v14.1.0) 🚀

Please let me how it goes!
