### ISSUE TITLE
Passing fetch:null in the options for createUploadLink results in an apollo NetworkError on first call.

### ISSUE THREAD

**Issue by parktheredcar** [jaydenseric/apollo-upload-client#167]
If drop-in HttpLink compatability is a goal, a null value for `fetch ` in the settings should fall back to the global value `window.fetch`. While it may be up for debate how one should handle incoming null values on an options object, HttpLink seems to do a check for null or undefined while apollo-upload-client is only checking for undefined. This means the same options object that will work for HttpLink will not work for the apollo-upload-client's link. 

I can't think of a scenario where someone would actually want their fetch client to be null so it seems like a minimal change.

To reproduce:

```
const fileUploadLink = createUploadLink({fetch:null});
// ... later, once your client is built make a request and it will fail.
```

> NetworkError: 'linkFetch' is not a function.

**Comment by kachkaev** [comment]
Same here. I was using this example:
https://github.com/zeit/next.js/blob/ab95c6d9a1ae10ff0703bebf5b38bc8ce3526e12/examples/with-apollo/lib/init-apollo.js#L12-L17

However, my link looked like this:

```ts
link: createUploadLink({
  uri,
  // Use fetch() polyfill on the server
  fetch: !isBrowser && fetch,
  }),
),
```

Only after ensuring that fetch is undefined and not false, my app worked:

```diff
-fetch: !isBrowser && fetch,
+fetch: !isBrowser ? fetch : undefined,
```

IMO a falsy value can be safely treated as undefined.

**Comment by jaydenseric** [comment]
Thanks for raising this issue for discussion; I've given it a fair bit of thought.

While `apollo-link-http` compatibility is somewhat a goal, it is not a requirement. Apollo packages have plenty of bugs and quirks, so if some can be mitigated here we should.

I searched the Apollo Link repo tests, and couldn't find any evidence Apollo intend for people to use falsy values for the `fetch` options. In fact, the value `false` is incorrect according to the TypeScript types:

<img width="1022" alt="Screen Shot 2019-12-02 at 5 17 05 pm" src="https://user-images.githubusercontent.com/1754873/69935239-61171800-1528-11ea-8784-4dbd94e65136.png">

While `null` doesn't appear to cause a TypeScript error, the docs don't explicitly mention it or use it in any examples:

https://www.apollographql.com/docs/link/links/http/#options

Maybe `null` works by design, but either way my preference is to continue relying on standard destructured parameter default value behavior: Only `undefined` triggers the default.

If this turns out to be problematic over time, we can reconsider.
