### ISSUE TITLE
Upload via WebSocket?

### ISSUE THREAD

**Issue by nuragic** [jaydenseric/apollo-upload-client#176]
Hello,

As far as I understand, if you have [the following setup](https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport) (AKA "full websocket transport") is not possible right now to send files with this link.

Do you think it would be possible to add support for uploading files via WebSocket?

Thanks!

**Comment by dko-slapdash** [comment]
I think it's technically impossible to upload via WS (and even uploading via fetch() - which is implemented in apollo-upload-client - is not perfect since it e.g. doesn't support upload progress).

But we do this:

![image](https://user-images.githubusercontent.com/46383452/75226834-e5f98280-5761-11ea-8558-261197d2d895.png)

**Comment by nuragic** [comment]
What do you mean by technically impossible? It is indeed possible to send binary data over WS… you can use `FileReader` APIs on the client to read the file and send it to the WS server. You can also `slice` the file and send it in various pieces.

**Comment by jaydenseric** [comment]
`apollo-upload-client` is specifically a [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec) compliant solution, compatible with lots of server [implementations of the spec](https://github.com/jaydenseric/graphql-multipart-request-spec#implementations).

While it might be possible to come up with a different solution for WebSockets (here or elsewhere), it's not something I am super keen to do myself until there is a robust GraphQL WebSocket protocol endorsed by the GraphQL foundation (which might be years away) instead of building on top of the shaky Apollo protocol and packages. For [similar reasons](https://github.com/jaydenseric/graphql-react/issues/15#issuecomment-590759131) I haven't yet supported subscriptions in [`graphql-react`](https://github.com/jaydenseric/graphql-react).

**Comment by nuragic** [comment]
Ok many thanks for the clarification! 

> until there is a robust GraphQL WebSocket protocol endorsed by the GraphQL foundation (which might be years away) instead of building on top of the shaky Apollo protocol and packages

What do you mean with "endorsed by the GraphQL fundation"? What should happen? Just curious... it would be nice to make it happen. Also, there's already any WIP on this?

**Comment by jaydenseric** [comment]
@nuragic 

> What do you mean with "endorsed by the GraphQL fundation"?

The [GraphQL Foundation](https://foundation.graphql.org) is the source of truth for GraphQL standards. At the moment, there is an official [GraphQL spec](https://github.com/graphql/graphql-spec) but no formal spec for making GraphQL network requests. A spec for [GraphQL over HTTP is in the works](https://github.com/APIs-guru/graphql-over-http/blob/master/ROADMAP.md) (which I happen to be involved in), but an official WebSocket protocol is more complicated and to my knowledge is not being worked on yet.

**Comment by nuragic** [comment]
Ok, thanks! I guess that "might be years away" as you said, or it may be not included at all in the spec... perhaps we'll keep using custom WS protocols forever, who knows? 😄
