### ISSUE TITLE
Variable "$file" got invalid value {}; Expected type Upload. Upload value invalid.

### ISSUE THREAD

**Issue by ysz** [jaydenseric/apollo-upload-client#180]
I tried to run your example app from https://github.com/jaydenseric/apollo-upload-examples against repro server here https://github.com/ysz/apollo-server-upload

It does not work and Apollo server says:

```
[GraphQLError: Variable "$file" got invalid value {}; Expected type Upload. Upload value invalid.] {
  message: 'Variable "$file" got invalid value {}; Expected type Upload. Upload value invalid.',
  locations: [ { line: 1, column: 23 } ],
  path: undefined,
  extensions: {
    code: 'INTERNAL_SERVER_ERROR',
    exception: { message: 'Upload value invalid.', stacktrace: [Array] }
  }
}

```

Apollo server is configured like this:

```
const server = new ApolloServer({
  uploads: {
    // https://github.com/jaydenseric/graphql-upload#type-processrequestoptions
    maxFileSize: 10000000, // 10 MB
    maxFiles: 20
  },
  typeDefs,
  resolvers,
  formatError: (err: any) => {
    console.log(err);

    // Otherwise return the original error.  The error can also
    // be manipulated in other ways, so long as it's returned.
    return err;
  }
});
app.use(
  /*'/foo/graphql',*/
  /* graphqlUploadExpress({maxFileSize: 10000000, maxFiles: 10}),*/
  server.getMiddleware({ path: "/foo/graphql" })
);
```

**Comment by jaydenseric** [comment]
I don't think that is an `apollo-upload-client` issue, most likely there are multiple conflicting versions of `graphql-upload` installed in the server. In the server project, run `npm ls graphql-upload` to check. Apollo Server uses a significantly outdated version, which can lead to issues if you try installing a newer one as a dependency.

**Comment by jaydenseric** [comment]
Yep: https://github.com/ysz/apollo-server-upload/blob/master/package.json#L10

**Comment by saostad** [comment]
mine was because of 
```
`-- apollo-server-express@2.13.0
  `-- apollo-server-core@2.13.0
    `-- graphql-upload@8.1.0
```

**Comment by alexisdray** [comment]
sorry to create noise on an old issue: 
we have this same problem we have graphql-upload@11x  as a depedency of graphql-tools / graphql cli 
like saostad we have 

`-- apollo-server-express@2.13.0
  `-- apollo-server-core@2.13.0
    `-- graphql-upload@8.1.0
    
    
    verified that when we remove graphql-tools  /  graphql cli 
    and therefore remove double version graphql-upload, the issue is resolved. 
    however quite dependent on these packages in our workflow currently. 
    
    is this the only solution? (or downgrading graphql-tools  all the way down to where their deps are inline with apollo-server-core) 
    is there another way to reconcile the package version differences?

**Comment by jaydenseric** [comment]
@alexisdray I don't have any of those problems because I don't use Apollo Server anymore, I use [`graphql-api-koa`](https://github.com/jaydenseric/graphql-api-koa).

People who are stuck using Apollo Server because of work or something have had luck using Yarn resolutions (or a similar feature in cutting edge npm) to force `graphql-upload` and `fs-capacitor` to install at newer versions. But it's better to disable the built in `graphql-upload` integration, and do a manual setup. There is an example here:

https://github.com/jaydenseric/apollo-upload-examples/blob/c456f86b58ead10ea45137628f0a98951f63e239/api/server.js#L78-L81

I'm not sure what value you get out of using `graphql-tools`, presumably to define your schema using SDL strings? If so, you’re far better off constructing your schema in a modular way using vanilla JS modules and GraphQL.js.

**Comment by alexisdray** [comment]
@jaydenseric i realize this wasn't an issue directly related to apollo-upload-client. 
thank you so much for taking the time to respond anyway to my question
