### ISSUE TITLE
Right approach to do 100s of images

### ISSUE THREAD

**Issue by naishe** [jaydenseric/apollo-upload-client#181]
I am working on an app that requires to upload 100s of images in one go (a visual storybook) by the authors. I initially implemented a multiple-upload mechanism, but I realized it may not be the best idea because if for some reason, the upload failed midway:
1. I would not know what files are done and what not.
2. I cannot retry individual images (I am using React Dropzone)

So, I am calling single upload mutation in a loop, serially, and showing the status and retry in case of failure. Essentially this:

```tsx
const uploadFiles = async () => {
    for (let i = 0; i < files.length; i++) {
       // [--- snip: logic to set which file is being uploaded to show spinner/retry etc ---]
       await uploadSingleFile({ variables: { file: files[i]} });
      // catch and handle error, retry
    }
  };
```

This looks way too simple to feel like I am ignoring something. Is there a suggestion on how to do it better?

**Comment by mike-marcacci** [comment]
This is probably not the best place for this kind of question, since this is NOT an issue with the library. However, I will note that most browsers limit a page's network concurrency to 4, so you could maximize your throughput by using 4 "workers" (1 for each connection) that consume files from the list as they finish their previous file.

**Comment by naishe** [comment]
Thanks for the tip. Please feel free to close this, I agree with you -- it is not an issue.
