### ISSUE TITLE
'Unknown browser Node' after updating to v14

### ISSUE THREAD

**Issue by egges** [jaydenseric/apollo-upload-client#208]
I get an error 'Unknown browser Node' after updating to v14. I'm on Node version 12.18.2 (Mac), using Parcel as a bundler. Reverting to v13 solves the issue.

**Comment by jaydenseric** [comment]
What makes you think this is a problem with `apollo-upload-client`, and not Parcel?

**Comment by jaydenseric** [comment]
This is because Parcel seems to be using an outdated version of `browserslist`, or is misusing the browserslist API to not account for modern browserslist queries containing `node` parts:

https://github.com/jaydenseric/apollo-upload-client/blob/808246d59ee1184c0aed0cf40720a8e5770d2085/package.json#L46

This is not an issue with `apollo-upload-client`, we are using browserslist correctly:

https://github.com/browserslist/browserslist#browsers

Perhaps check Parcel issues and raise one if they are not aware of this yet :)

**Comment by egges** [comment]
Thanks, Jayden, I'll post an issue with them!
