### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by robphoenix** [jaydenseric/apollo-upload-client#210]
Hi, I'm getting the following error: `POST body missing. Did you forget use body-parser middleware?`

App.tsx
```ts
const client = new ApolloClient({
    cache: new InMemoryCache(),
    link: createUploadLink({
      uri: window.GRAPHQL_URI,
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }),
  })
```

file upload hook
```ts
const mutation = gql`
  mutation($fileInput: FileInput!) {
    uploadFile(fileInput: $fileInput) {
      key
    }
  }
`

const useFileUpload = () => {
  const [mutate, { data, loading, error }] = useMutation(mutation)

  const uploadFile = (fileInput: FileInput) => {
    return mutate({
      variables: { fileInput },
      fetchPolicy: `no-cache`,
    })
  }

  return {
    data,
    loading,
    error,
    uploadFile,
  }
}
```

GraphQL schema
```ts
type Mutation {
  uploadFile(fileInput: FileInput!): File
}


input FileInput {
  file: Upload!
  name: String!
  prefix: String!
}
```

server.ts
```ts
import { ApolloServer, AuthenticationError } from 'apollo-server-express'
import { IncomingMessage } from 'http'
import path from 'path'
import express from 'express'
import { loadSchemaSync } from '@graphql-tools/load'
import { GraphQLFileLoader } from '@graphql-tools/graphql-file-loader'
import { addResolversToSchema } from '@graphql-tools/schema'
// import { graphqlUploadExpress } from 'graphql-upload'

import resolvers from './resolvers'
import authenticate from './auth'

const context = async ({ req }: { req: IncomingMessage }) => {
  const token = req.headers.authorization || ''
  try {
    await authenticate(token)
  } catch (error) {
    throw new AuthenticationError(error)
  }
}

const options = { port: process.env.PORT || 3001 }
const schema = loadSchemaSync(
  // the path needs to be relative to the build output
  path.join(__dirname, `..`, `src`, `schema.graphql`),
  { loaders: [new GraphQLFileLoader()] }
)
const schemaWithResolvers = addResolversToSchema({
  schema,
  resolvers,
})

const server = new ApolloServer({
  uploads: false,
  schema: schemaWithResolvers,
  context,
})

const app = express()

// file uploads
// app.use(graphqlUploadExpress())

if (process.env.NODE_ENV !== `local`) {
  const buildPath =
    process.env.BUILD_ENV || path.join(__dirname, `../../app/build`)

  app.use(`/`, express.static(buildPath))
  app.use(`*`, express.static(buildPath))
}

server.applyMiddleware({
  app,
  bodyParserConfig: {
    limit: `15mb`,
  },
})

app.listen(options, () => {
  if (process.env.NODE_ENV === `local`) {
    console.log(
      `\n🚀  GraphQL Playground is running on http://app.local.uw.systems:${options.port}${server.graphqlPath}`
    )
  }
})
```

The resolver is not getting called at all. It works if I use `graphql-upload`. Am I missing something or am I supposed to be using `graphql-upload` alongside this library?

Thanks

**Comment by jaydenseric** [comment]
```js
const server = new ApolloServer({
  uploads: false,
  schema: schemaWithResolvers,
  context,
})
```

I see you are opting out of the built-in Apollo Server file uploads setup via `uploads: false`. [This is a good thing to do](https://github.com/apollographql/apollo-server/issues/3508#issuecomment-662371289), but then you then need to manually setup [`graphql-upload`](https://github.com/jaydenseric/graphql-upload#function-graphqluploadexpress). See here for a Koa example:

https://github.com/jaydenseric/apollo-upload-examples/blob/bff2ccf700eba8355c4e7469ee3b02e0c808f5bd/api/server.js#L77-L81

**Comment by robphoenix** [comment]
Thanks @jaydenseric for confirming that manually utilising `graphql-upload` is the way to go. 👍

**Comment by RAMPKORV** [comment]
Has someone successfully implemented this without layering an additional web server (express, koa ...) on top of Apollo Server?

**Comment by yassh-pandey** [comment]
My **server.js** file looks like this:
```javascript
const { ApolloServer, gql } = require('apollo-server');
const { GraphQLUpload } = require('graphql-upload');
const path = require('path');
const fs = require('fs');

const typeDefs = gql`
  scalar Upload 

  type File {
    filename: String!
    url: String!
  }

  type Query {
    hello: String
  }

  type Mutation {
    fileUpload(file: Upload!): File!
  }
`;

const resolvers = {
  Query: {
    hello: (parent, args) => 'Hello world!',
  },
  Mutation: {
    fileUpload: async (parent, args) => {
      console.log('Recieved a request for file upload')
      const { file } = args;
      const { filename, mimetype, createReadStream, encoding } = await file;  
      const stream = createReadStream()
      const pathName = path.join(__dirname, `public/images/${filename}`)
      await stream.pipe(fs.createWriteStream(pathName))
      return {
          filename,
          url: `http://www.localhost:4000/images/${filename}`
      }
    },
  },
  Upload: GraphQLUpload
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  uploads: false
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});


```
If I use the default scalar that apolo-server provides then it's working fine but I am getting the same error as @robphoenix when I opt out of built-in **Apollo Server file uploads** setup. 
Anyone with an idea of what am I doing wrong here?
The server doesn't break apparently but I am getting this on the client as the response. 

![GQL File Upload Error](https://user-images.githubusercontent.com/20154348/122657056-a5efb780-d17d-11eb-850b-ec04f6cc1da9.png)

**Comment by jaydenseric** [comment]
@yassh-pandey you need to follow the [`graphql-upload` setup instructions](https://github.com/jaydenseric/graphql-upload#setup) properly; you're not using any of the middleware that processes the request.

**Comment by yassh-pandey** [comment]
So we can't use it directly like that but need to use express or koa middleware that support GraphQL multipart requests using processRequest. 
Got it, thanks. 🙏
I wish there was a simplified example in which we aren't using the GraphQLObjectType to create mutation but simply using the gql`` syntax. And if that contrived example could be contained in a single file (less context switching). I'll try to do it and if it works for me I can create a PR if you think it'll help others.

**Comment by jaydenseric** [comment]
@yassh-pandey 

> So we can't use it directly like that but need to use express or koa middleware

One way or another, you need to process the request to prepare the values for the `Upload` scalars in your resolvers. That's the whole point of `graphql-upload`; it processes multipart requests. You don't need to use the published Koa or Express middleware if you don't use either in your backend; for most people the middleware is really handy but you're free to use `processRequest` directly if you prefer.

The middleware is pretty simple:

https://github.com/jaydenseric/graphql-upload/blob/bdb5f808e0d514c28c0f59c1abd71680aba29bae/public/graphqlUploadKoa.js#L53-L68

It does 2 things (only for multipart requests):

1. It uses `processRequest`.
2. It makes sure that a response is not sent until the request has finished. This would only happen if there is some sort of error is thrown in the resolvers (e.g. for an argument validation or authorization error) because when resolvers work smoothly all of the individual file upload streams, and therefore the entire multipart request stream, should be awaited. Technically it's valid in HTTP to send a response before the request has finished uploading, but most browsers incorrectly bug out in such a situation and `fetch` for example can explode in weird ways. You may choose not to implement this feature when manually implementing `processRequest`.

> I wish there was a simplified example in which we aren't using the GraphQLObjectType to create mutation but simply using the gql`` syntax.

Having worked on GraphQL APIs for years on end, at first constructing schemas via separate GraphQL SDL strings and resolver code, and then the proper `graphql` JS API way, I came to the solid conclusion that the JS way is far superior in every way. It's faster, requires less dependencies and tooling, is easier to work with (especially when adding custom scalars or modularizing your code), and is less bug prone as you don't have to try to manually sync strings and JS code that relate to each other across separate files. I encourage the GraphQL community to adopt the original way schemas were composed using JS modules before Apollo normalized using strings everywhere. To that end, example code in any of my projects will only be done the more optimal way.

**Comment by yassh-pandey** [comment]
@jaydenseric Thanks for the detailed response. I get it now. Unlike you I am new to GQL, so I'll try to implement what you suggested. 🙌
