### ISSUE TITLE
Send file to remote API (i.e. straight pass through)

### ISSUE THREAD

**Issue by huevoncito** [jaydenseric/apollo-upload-client#219]
Thanks for this super helpful package.

I'm uploading the file successfully to Apollo Server, but my use case is to send the file to a remote API which happens to be an express app. However the "file" that hits our Apollo Server isn't actually a file, it's the object that this package produces after the upload. So we're kind of stuck. How can I simply pass the uploaded file through to another endpoint?  

The idea is to send the file using the Apollo Datasource class which basically extends fetch:

```javascript

class MyDataSource extends RestDataSource {
   constructor() {
     //... blah blah blah
  }
  sendFileToRemoteAPI(file) {
    //this is what we want to do, except "file" isn't a file, it's the object that results from the upload
    return this.post( '/api/endpoint/name', { file }, { headers: { "Content-Type": "text/csv" } } );
   }
}

```

Is there a simple way to convert the result of the upload into a file that the remote API will recognize as such?

Thanks again!

**Comment by jaydenseric** [comment]
Thanks for the kind words :)

Your question is actually about the server side of things, and this repo is for the client. It also seems extremely specific to Apollo Server APIs; it’s best to ask these questions wherever Apollo is happy to facilitate discussions about their server offerings. Although this repo has Apollo in the name (because it's an Apollo Client HTTP link) the requests that are sent are GraphQL server agnostic via the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec).

> However the "file" that hits our Apollo Server isn't actually a file, it's the object that this package produces after the upload.

A few things to clarify…

- "the "file" that hits our Apollo Server isn't actually a file" — yes it is a file, it's streamed in via a multipart form file field.
- "it's the object that this package produces" —  this package is not installed on the server. I think you are confusing it for [`graphql-upload`](https://github.com/jaydenseric/graphql-upload).
- "after the upload" —  `graphql-upload` middleware on the server will provide the `Upload` object (a promise) immediately, before any of the files start streaming in to the server; not after the upload has finished. You read the readable stream from it of the file that is streaming in.

> How can I simply pass the uploaded file through to another endpoint?

That depends on what sort of requests your endpoint supports. There are lots of ways you can make a multipart request to an endpoint in Node.js, given a readable stream of a file - I don't really have the availability to help you through all the options right now, sorry.

**Comment by lParraMediaCurrent** [comment]
Even if is true that this isn't something related with this specific package (and keep the issue closed is the best) I'm going to leave this piece of code of how to send the received file to a different api with axios

```javascript

const {createReadStream} = await input.file;
// Really important in order to read all the content of the file
const streamToRead = createReadStream({ encoding: 'binary'})
await new Promise(resolve => {
  streamToRead.on('data', () => {})
  streamToRead.on('end', resolve)
})

const data = new FormData()
data.append('file',  createReadStream({encoding: 'binary'}))

return axios({
  method: 'POST',
  url: 'my-url',
  headers: {
    ...data.getHeaders(),
    Authentication: 'dummy value'
  },
  data,
}).then(response => response.data)
```
