### ISSUE TITLE
How can we use it with Ink project

### ISSUE THREAD

**Issue by brunomacf** [jaydenseric/apollo-upload-client#228]
I'm using [ink](https://github.com/vadimdemedes/ink) to implement a cli app and i'm being able to make requests using apollo client just fine. But when trying to upload a file i'm getting into some trouble using apollo-upload-client. In a CLI env we don't have File, FileList, etc... i was looking at how apollo-upload-client extract files from apollo request body and it seems it just recognizes File, FileList, Blob and ReactNativeFile. The first 3 options are not available in a CLI (Nodejs) env... i tried to use ReactNativeFile in a hackish way here but with no luck. Is there a way to make this work?

**Comment by jaydenseric** [comment]
You achieve file uploads in a Node.js environment a few ways.

Since the tests run in Node.js you can look at them for nieve examples using `Blob`:

https://github.com/jaydenseric/apollo-upload-client/blob/7950946f8268b6d10ec84daa1e5b877c72f690f2/test/public/createUploadLink.test.js#L101

To use a Node.js readable stream as a file in variables, you will need to use a few of the [`createUploadLink` options](https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink).

These you can alternatively customize the globals, or use the options:

- `fetch` (e.g. [`node-fetch`](https://npm.im/node-fetch))
- `FormData` (e.g. [`formdata-node`](https://npm.im/formdata-node))

Then you should use these options:

- `isExtractableFile` (read the docs)
- `formDataAppendFile` (if you are doing someone very custom, maybe you don't need to use it?)

Note that I recommend against using Apollo Client for making GraphQL requests on the server - why do you want to use it in the first place? Habit? To avoid all the extra bundle size bloat and the performance overhead of cache, observables, etc. just make a [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure) manually using `fetch` and `FormData` directly.

**Comment by brunomacf** [comment]
@jaydenseric thanks a lot for reply... i was able to do upload with read stream doing like you said:

```
import fs from "fs";

import { createUploadLink, isExtractableFile } from "apollo-upload-client";
import fetch from "cross-fetch";
import FormData from "form-data";

const httpLink = createUploadLink({
      fetch,
      FormData, 
      isExtractableFile: (value: any) =>
        isExtractableFile(value) || value instanceof fs.ReadStream,
      uri: config.httpUri,
    } as any) as any;
```

And i'm using apollo-client bc i'm using some of it's features like pooling but i going to consider droping it and making graphql requests directly to avoid this extra layer. Thanks a lot for the reply man :)
