### ISSUE TITLE
Can not compile with typescript, module resolution failed with "extract-files" package.

### ISSUE THREAD

**Issue by fellz** [jaydenseric/apollo-upload-client#230]
Hi
There was an issue with this lately but it was resolved in CRA webpack config. As that config can read and understand only senior webpack devs i couldn't find the place where they fixed that issue. So what exactly should i write in webpack config to solve that issue ? 
```Module not found: Error: Can't resolve 'extract-files/public/ReactNativeFile'```
```Module not found: Error: Can't resolve 'extract-files/public/extractFiles'```
```Module not found: Error: Can't resolve 'extract-files/public/isExtractableFile'```

thanks
I guess it's tsc that cann't resolve commonJS modules.

**Comment by jaydenseric** [comment]
`apollo-upload-client` and `extract-files` are using 100% standard Node.js patterns for publishing a package, so if you are having problems bundling them chances are you'll encounter issues with a lot of other packages too.

I really can't help you fix your webpack config; sorry! It is way too project specific, and is not an issue with this package.

Feel free to share the solution to your problem here though, in case it helps others.

**Comment by mike-marcacci** [comment]
Hi @fellz, I don't believe this is due to tsc, but rather webpack. While I no longer use this package in any of my projects, I do use others that depend on `extract-files` and upgrading them from webpack 4 to webpack 5 results in this issue. This is likely an issue with Webpack's module loading implementation; the whole esm/commonjs story is a mess throughout the ecosystem right now.

Anyway, I haven't invested much in fixing this, as I don't have an immediate need to upgrade from webpack 4, but figure I could nudge you in the right direction.

**Comment by fellz** [comment]
> Hi @fellz, I don't believe this is due to tsc, but rather webpack. While I no longer use this package in any of my projects, I do use other libraries that depend on `extract-files`. Upgrading those projects from webpack 4 to webpack 5 result in this issue. This is likely an issue with Webpack's module loading implementation; the whole esm/commonjs story is a mess throughout the ecosystem right now.
> 
> Anyway, I haven't invested much in fixing this, as I don't have an immediate need to upgrade from webpack 4, but figure I could nudge you in the right direction.

Yes, webpack 4 solved problem. Webpack 5 version doesn't support Node API polifills.
