### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by olivierlacan** [jaydenseric/apollo-upload-client#233]
Although "MIT" is listed in this project's package.json, there is no LICENSE file with a copyright listing. Is that intentional? https://choosealicense.com/licenses/mit/

https://github.com/jaydenseric/apollo-upload-client/blob/7950946f8268b6d10ec84daa1e5b877c72f690f2/package.json#L5

**Comment by jaydenseric** [comment]
Yes, this is intentional.

One of the reasons that I don’t include a license file (relying on the license relate fields in package.json instead) is that doing so would bloat the install size of the package in `node_modules`; npm always publishes license files if they exist. Also, having hardcoded years in license files that need to be updated across many packages is a maintenance burden.

**Comment by olivierlacan** [comment]
While I understand why that might feel like an overly large burden as a maintainer. Listing "MIT" in packages.json is not equivalent to publishing a license either in your README or as a standalone file with a copyright notice. 

You may have listed `MIT` but you currently don't comply with the MIT license's own terms and therefore your repository and software are effectively unlicensed: 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

That would be an issue for anyone distributing software which depends on this code and for which they would be required to disclose any license that might exist (in order to comply with licensing requirements).

**Comment by jaydenseric** [comment]
> Listing "MIT" in packages.json is not equivalent to publishing a license either in your README or as a standalone file with a copyright notice.

Are you sure?

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

In a pretty strong way I am including the notice in all copies of the software I publish. The source of truth about the authorship and licencing of an npm package is the contents of `package.json`. The SPDX `MIT` short identifier in the `licence` field holds the same meaning as the full text of the MIT licence, with the caveat that the `author` field has to also be used to imply the author in the MIT licence. The year for the licence is not _strictly_ required, depending on jurisdiction, etc. (googling around _apparently_ it only matters in the US for corporations, not individuals who are the licence holders) but regardless, it can be implied by the published date of the package. While technically I could publish unchanged code infinite times across multiple years, in practice I only publish a new version when the software has changed.

At the end of the day, if it's determined that my software is unlicensed due to a legal technicality in a particular jurisdiction it would only be me you have to worry about; and I'm a pretty reasonable guy. I won't go after honest users. If someone blatantly copies my work and tries to pass it off as if they are the original author, then I might get mad.

Copyright stuff is all a bit bullshit and up for interpretation. For example, users can import a "substantial portion" of the `apollo-upload-client` by doing a deep import from UNPKG:

https://unpkg.com/browse/apollo-upload-client@14.1.2/public/createUploadLink.js

Is UNPKG in breach for distributing this code, either if the software is unlicensed, or if it's MIT but they are not displaying the licence with the distributed code? Should I include the full MIT licence as a comment at the top of all of the distribution files? Minifiers preserve licence comments, and the bundle size of this package will go through the roof - maybe a 10x increase. If you strip all comments when bundling this package, would you be in violation of the MIT licence? Regardless if I put licence comments in the published code, if I were to include a licence file in the repo, people bundling without manually inserting my licence are in violation. Yet no one does this. Intellectual property stuff is a house of cards.

My software has been installed over 100 million times this past year alone, and I have only received one email from someone asking to clarify in writing the licence text (with author name and year) which I happily replied with. I'm not outright refusing to put a licence file in my repo, but I won't rush out and blindly create work (adding licence files, updating licence year each year) or introduce technical issues (licence comments in bundles, licence files in `node_modules`) just to put a corporate lawyer somewhere at ease — not a single company that profits from my work has sponsored my open source. I'm about improving the lives of real people and making the world a better place, and if adding a licence file will make life easier for thousands of users I totally would. I'm just not convinced yet it's something they need, or more people would have asked for it by now. It seems everyone is happy to read the `package.json` (or use auditing software to do it) and understand the terms.

If I change my mind I would not just add the licence file in the repo, but in all of the repos I maintain. I don't mean to give you a hard time; continued discussion is welcome :)

**Comment by mykelswitzer** [comment]
>The SPDX MIT short identifier in the licence field holds the same meaning as the full text of the MIT licence, with the caveat that the author field has to also be used to imply the author in the MIT licence.

do you have a reference that supports this?
