### ISSUE TITLE
[Error: JSON Parse error: Unrecognized token '<']

### ISSUE THREAD

**Issue by LaurenceSM10** [jaydenseric/apollo-upload-client#234]
I am getting this error when executing uploadFile mutation from React Native. Any ideas on what could be causing the error?

```

const file = new ReactNativeFile({
          uri: result.uri,
          name: result.name,
          type: 'image/jpeg',
});

await uploadFile(file);
```

**Comment by jaydenseric** [comment]
Try to use a network inspector to read what the response body for the GraphQL request is; usually when you get a message like that it's because the server is sending back a HTML error page that begins with `<!DOCTYPE html>`. There is not enough information for me to be able to tell what your server error is, but often it's because you need to authenticate or something.

Note that some dev tools for React Native can interfere with network requests - particular multipart ones.

**Comment by Gogul-S** [comment]
@jaydenseric 

I am facing this error intermittently, this is the error object I get in client

`{
    "graphQLErrors": [],
    "networkError": {
      "name": "ServerParseError",
      "response": {
        "type": "default",
        "status": 403,
        "ok": false,
        "statusText": "",
        "headers": {
          "map": {
            "server": "awselb/2.0",
            "content-type": "text/html",
            "date": "Mon, 09 Aug 2021 08:30:05 GMT",
            "content-length": "118"
          }
        },
        "url": "****",
        "bodyUsed": true,
        "_bodyInit": {
          "_data": {
            "size": 118,
            "offset": 0,
            "blobId": "****",
            "__collector": {}
          }
        },
        "_bodyBlob": {
          "_data": {
            "size": 118,
            "offset": 0,
            "blobId": "****",
            "__collector": {}
          }
        }
      },
      "statusCode": 403,
      "bodyText": "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
    },
    "message": "Network error: JSON Parse error: Unexpected token: <"
  }`
