### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by acomito** [jaydenseric/apollo-upload-client#238]
I'm getting this error when I try to upload a large PDF...

The error is:

`
Access to fetch at 'https://api.herokuapp.com/graphql' from origin 'https://app.website.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

What's strange:

- It works when I'm locally running my frontend (create-react-app) and backend (node/apollo-server)
- The error only happens on our live server(backend on heroku)
- I have another app with almost the identical setup, and I don't get this error there (same client/server setup and works when hosted on heroku)
- It only happens with larger files, like 40kb and over... otherwise it uploads anything less than that okay

**Comment by mike-marcacci** [comment]
Hi @acomito, This is _almost certainly_ not a bug in this library but instead the with your live setup (as I'm sure you've gathered). Based on your observation that only larger uploads are experiencing this issue, I would check to see if the uploads are failing or returning, and the resulting response is simply missing the `Access-Control-Allow-Origin` header.

**Comment by jaydenseric** [comment]
In agreement with @mike-marcacci . Somewhere in your infrastructure for the GraphQL API server there might be either a request size or time limit being exceeded by the larger requests, and the error response doesn't have the right CORs headers.

You can try to configure your infrastructure to increase the relevant limits.

For better errors in the future, there are a few things you could do. If you use [`graphql-upload`](https://github.com/jaydenseric/graphql-upload) on the backend, be sure to configure `maxFileSize`, etc. in the [process request options](https://github.com/jaydenseric/graphql-upload#type-processrequestoptions) so you’re more likely to get a nicer GraphQL error response if file size is exceeded, instead of a default infrastructure error. For a timeout error, you could setup middleware to track the request time and respond with a nicer GraphQL error response if the infrastructure limit is getting close to being exceeded.

**Comment by acomito** [comment]
Hey @jaydenseric @mike-marcacci Sorry for the radio silence.

It seems to be something with heroku. My app works locally and it works on the google app engine.

I'm using a newer version of apollo-server which has uploading built in already (maybe it's graphql-upload under the hook I dont know).

Again, the strange thing is I have 3-4 other apps with the same setup running on heroku that are uploading files that this problem app can't.... so it's a strange situation.

Anyway, you're right definitely not an issue with apollo-upload-client. But I'll try to update this issue if I ever find out what's going on... in case it helps somebody else one day.

**Comment by jaydenseric** [comment]
> I'm using a newer version of apollo-server which has uploading built in already (maybe it's graphql-upload under the hood, I dont know).

They use [`graphql-upload`](https://github.com/jaydenseric/graphql-upload) under the hood, but unfortunately it's a very old version. You should disable their implementation and manually setup file uploads using the latest [`graphql-upload`](https://github.com/jaydenseric/graphql-upload) version.

**Comment by kumasan3** [comment]
Hello
It happened when
- Cross Origin Request
- But you set CORS header setting at your application server level.
- And file get split because it's too large, and first request with the first part of the file got received by your **web server** first, and responded without CORS headers.
- I think most of web server will keep responding until the rest parts of the files arrive, and send one large request to your application server.

I observed that it happened only when the file got split, and only when using Nginx in my case.

The solution could be
* Stop cross origin
* change your web server setting somehow to always set CORS headers even on the multi-part request
