### ISSUE TITLE
Updating the headers on each request.

### ISSUE THREAD

**Issue by Stivi7** [jaydenseric/apollo-upload-client#245]
In the existing docs the way the headers are passed, are only set the first time when client loads. How can I set up the apollo upload client so the headers get updated on each request. I need to use the authorization token. The problem is that when the app loads at first the token is still not initialized (user needs to login). After logging in there is no way to pass the token to the apollo upload client.
How can i solve this issue?

Here it is the client config that I have:

```
import {
  ApolloClient,
  InMemoryCache,
} from '@apollo/client';
import { createUploadLink } from 'apollo-upload-client';
import { getStoredToken } from '../context/auth';

export default new ApolloClient({
  cache: new InMemoryCache(),
  link: createUploadLink({
    uri: process.env.GRAPHQL_URL,
    headers: {
      authorization: getStoredToken(),
    },
  }),
});
```

Thanks!

**Comment by jaydenseric** [comment]
You can use an Apollo Link to set a custom header in the context per request, as per the Apollo Client docs:

https://www.apollographql.com/docs/react/networking/authentication/#header

The difference with that example is that the `httpLink` is created using `createUploadLink` instead of `createHttpLink`.

**Comment by Stivi7** [comment]
Thank you very much!!
