### ISSUE TITLE
upload file and video not work (image upload work fine)

### ISSUE THREAD

**Issue by shipcake** [jaydenseric/apollo-upload-client#253]
Hi. I have problem
[https://youtu.be/sUC9-3hAX8Y](url)

My resolver nothing process it.

```
export const newclaim = async (_, { input }, ctx) => {
    try {
        return true
    } catch (err) {
        console.log(err)
    }

}
```

_app.tsx
`const httpLink = createUploadLink({
  uri: '/api/graphql',
  credentials: "include",
  fetch,
})`

**Comment by jaydenseric** [comment]
> My resolver nothing process it.

I'm confused. In the resolver code you shared you don't do any processing of the upload, so why do you expect it to magically be processed? That `try`/`catch`code doesn't even do anything so why share it here in this issue?

If you are having problems, the first thing you can do is check using the browser network inspector if the GraphQL request is a valid [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec). If it is, the problem is your server. If it isn't, then look at your client code; particularly the `apollo-upload-client` setup and also how you are populating the mutation variables for uploads; are they really `File` or `Blob` instances like you think they are.

**Comment by shipcake** [comment]
It test resolver connecting receive video file . if work I continue other process in resolver (image work I test write to file system)

in my schema
`  filesvideo:Upload`

my _app error handler

`const errorLink: any = onError(({ graphQLErrors, networkError }) => {

  if (graphQLErrors) {
    graphQLErrors.map((err) => {
      if (networkError) {

        console.log("1")
        console.log(err)
        return toast.error(err.toString())
      } else {
        const hand = Error_Handler(err)

        console.log("2")
        console.log(err)
        return toast.error(hand)
      }
    })
  }
  if (networkError) {
    console.log(networkError)
  }
})`

my _app 
`const Client = new ApolloClient({
  ssrMode: true,
  link: from([errorLink, httpLink]),
  // link: createUploadLink(),
  cache: new InMemoryCache() //memory cache,
})`

no anything show in error log just pendding...

**Comment by jaydenseric** [comment]
Why do you comment such poorly formatted code?

<img width="400" alt="Screen Shot 2021-03-31 at 8 04 02 pm" src="https://user-images.githubusercontent.com/1754873/113119693-773c0200-925c-11eb-8991-c702936b5a66.png">

Please edit your comment and tidy the code so we can actually read it:

<img width="261" alt="Screen Shot 2021-03-31 at 8 07 07 pm" src="https://user-images.githubusercontent.com/1754873/113119922-b79b8000-925c-11eb-81c3-cce02173ed93.png">

**Comment by shipcake** [comment]
Sorry sir. I edit my posted.

**Comment by shipcake** [comment]
my other project everything work fine because I only upload image .jpg .png. but this project is important to upload mini video file keep in server (less 50MB). I try to search sulotion in this repo but nothing who issue same me :( 
sorry I bad english.

**Comment by shipcake** [comment]
plese check my video sometime work and or not?

[https://youtu.be/PCkF_66OuuQ](url)
