### ISSUE TITLE
Unable to install in a svelte + snowpack project 

### ISSUE THREAD

**Issue by sameerveda** [jaydenseric/apollo-upload-client#257]
Getting this error
```shell
[12:26:00] [snowpack] Package "extract-files" exists but package.json "exports" does not include entry for "./public/ReactNativeFile".
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

![image](https://user-images.githubusercontent.com/22796631/116035194-329c5e80-a682-11eb-81ce-c4d6f7ae6fbd.png)

```
apollo-upload-client@^14.1.3:
  version "14.1.3"
  resolved "https://registry.yarnpkg.com/apollo-upload-client/-/apollo-upload-client-14.1.3.tgz#91f39011897bd08e99c0de0164e77ad2f3402247"
  integrity sha512-X2T+7pHk5lcaaWnvP9h2tuAAMCzOW6/9juedQ0ZuGp3Ufl81BpDISlCs0o6u29wBV0RRT/QpMU2gbP+3FCfVpQ==
  dependencies:
    "@apollo/client" "^3.2.5"
    "@babel/runtime" "^7.12.5"
    extract-files "^9.0.0"
```

```
"@apollo/client@^3.2.5", "@apollo/client@^3.3.15":
  version "3.3.15"
  resolved "https://registry.yarnpkg.com/@apollo/client/-/client-3.3.15.tgz#bdd230894aac4beb8ade2b472a1d3c9ea6152812"
  integrity sha512-/WQmNvLEZMA0mA3u+FkEPTXKzxZD/KhyO7WlbKcy3zKGrXKza83tAbNMzsitQE7DTcSc3DLEcIu1Z5Rc7PFq0Q==
  dependencies:
    "@graphql-typed-document-node/core" "^3.0.0"
    "@types/zen-observable" "^0.8.0"
    "@wry/context" "^0.6.0"
    "@wry/equality" "^0.4.0"
    fast-json-stable-stringify "^2.0.0"
    graphql-tag "^2.12.0"
    hoist-non-react-statics "^3.3.2"
    optimism "^0.15.0"
    prop-types "^15.7.2"
    symbol-observable "^2.0.0"
    ts-invariant "^0.7.0"
    tslib "^1.10.0"
    zen-observable "^0.8.14"
```

**Very low priority, Just wanted to know if there is any solution for this.**

Currently using a forked version of this. 
https://github.com/jaydenseric/apollo-upload-client/compare/master...sameerveda:master

**Comment by jaydenseric** [comment]
This might not be the main problem, but this change doesn't look right, it's not exporting the right thing:

https://github.com/jaydenseric/apollo-upload-client/compare/master...sameerveda:master#diff-d83f9b79d29452dc0706b52de1e60ece5579610e2381f0ce86e55ce622043689R29

Note that I am sweeping across all of my 20+ packages and am replacing the the `package.json` `exports` field public [subpath folder mapping](https://nodejs.org/api/packages.html#packages_subpath_folder_mappings) (deprecated by Node.js) with a [subpath pattern](https://nodejs.org/api/packages.html#packages_subpath_patterns). This might relate to your issue; either because I haven't done it yet and a tool expects the new way, or because I have and the tool doesn't expect the new way.

`extract-files` v10 will have this change (it's not published yet):

https://github.com/jaydenseric/extract-files/blob/master/changelog.md#next

Once it's published, I'll update `apollo-upload-client` too.

Be sure to use the file extensions for your deep import paths importing from any of my packages, because they will become mandatory even for `require` with the new subpath patterns.

**Comment by sameerveda** [comment]
Thanx. Will be waiting for the update 

https://github.com/jaydenseric/apollo-upload-client/compare/master...sameerveda:master

**Comment by jaydenseric** [comment]
Cool :) As a tip though, always use deep import or require paths as that’s the most reliable way to ensure only the right things are imported and bundled, without relying on complicated tree-shaking or code-splitting abilities of your bundler. An example of buggy tooling: Next.js incorrectly bundles copies of things twice if you use a deep import in your `pages/_app.js` and a named import of the same thing in `pages/index.js` (or vice-versa).
