### ISSUE TITLE
upgraded to v15 breaks build

### ISSUE THREAD

**Issue by ljmerza** [jaydenseric/apollo-upload-client#263]
updated to latest version:

```
"apollo-client": "^2.6.10",
"apollo-link-context": "^1.0.20",
"apollo-link-http": "^1.5.17",
"apollo-upload-client": "^15.0.0",
```

but now get an error on build: 

```
.\node_modules\apollo-upload-client\public\createUploadLink.js
Cannot find module: '@apollo/client/core'. Make sure this package is installed.

You can install this package by running: npm install @apollo/client/core.
```

running `npm install @apollo/client/core` does not work. node v14

```
npm install --save @apollo/client/core
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@apollo\client\core" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-06-01T19_05_21_583Z-debug.log
```

**Comment by jaydenseric** [comment]
As documented in the [v15 release notes](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v15.0.0), `@apollo/client` v3 was changed from a dependency to a peer dependency:

https://github.com/jaydenseric/apollo-upload-client/blob/e9bf2aa218f8fdd291001de6ad0a2ba711c7bcad/package.json#L48

Your project has an `"apollo-client": "^2.6.10"` dependency, and `@apollo/client` v3 isn't installed. You should have seen a missing peer dependency warning from npm during install; always pay close attention to npm install messages.

It's actually lucky you ran into this problem, because it revealed you were using both Apollo Client v2 and v3 in the same app. Please migrate to `@apollo/client` v3.

Side note:

> You can install this package by running: npm install @apollo/client/core.

That's incorrect advice, looks like an npm bug. It should recommend installing `@apollo/client`, not `@apollo/client/core`.

**Comment by ljmerza** [comment]
thank you for the description
