### ISSUE TITLE
Question: how to set utf-8 encoding in the uploading file?

### ISSUE THREAD

**Issue by sakhmedbayev** [jaydenseric/apollo-upload-client#271]
I am uploading a text file using `apollo-upload-client`. When the file hits the server it comes in `7bit` encoding, e.g.:

```
const { filename, createReadStream, encoding } = await file;
console.log({ encoding });

--> { encoding: "7bit" }
```

I then make a stream as follow:

```
const stream = createReadStream({ encoding: "utf8" });
```

and then a string out for the stream using the following function:

```
function streamToString(stream, cb) {
  const chunks = [];
  stream.on("data", (chunk) => {
    chunks.push(chunk.toString());
  });
  stream.on("end", () => {
    cb(chunks.join(""));
  });
}
```
 
the result: 

```
streamToString(stream, async (data) => {
            
    console.log({data});

   --> good string �� good string ��

}
```

This is what gets saved in the DB `good string �� good string ��`.

I guess I need to send the file to the server with proper encoding, perhaps as `utf-8`. How can I do it?

**Comment by jaydenseric** [comment]
I've never really had encoding issues in any of my projects because almost always the files (e.g. images, PDF's, etc.) get streamed into S3-like storage, and I don't try to extract text out of the files for use in UTF-8 format.

Note that the `encoding` of the resolved `Upload` scalar refers to the `Content-Transfer-Encoding` for the multipart request file field stream, and doesn't refer to the encoding of the original file data. It's usually `7bit` and isn't really useful, I've never had a use for that information in any of my projects at least.

To clarify, your problem is you have a text file that is not UTF-8 encoded, but you want to get the text contents in UTF-8 format on the server after it's uploaded? It seems you have 2 options, either create a UTF-8 encoded text file on the client before uploading it, or somehow convert the format on the server. I'm not in a good position to give advice specific to your project how to do either of those things, but it sounds doable. I don't know if you can automatically detect the file format on the server while it's streaming in, or if you need the whole file buffered/stored, or if you can convert the format chunk by chunk as it streams in, or if you have to convert the whole file at once. I'd just be googling how to do it same as you.

I'm going to close this issue because the discussion doesn't relate to a bug or feature request, but feel free to share your findings here in case it helps others.

**Comment by sakhmedbayev** [comment]
In my case, the `streamToString` function was implemented incorrectly. Here is the correct version:

```
 const chunks = [];

  readStream.on("data", function (chunk) {
    chunks.push(chunk);
  });

  // Send the buffer or you can put it into a var
  readStream.on("end", function () {
    res.send(Buffer.concat(chunks));
  });
```
