### ISSUE TITLE
apollo-upload-client doesn't  have compatibility with apollo-client >= v3.5.0

### ISSUE THREAD

**Issue by pipopotamasu** [jaydenseric/apollo-upload-client#273]
HttpLink has accepts `print` option since apollo-client v3.5.0.
https://github.com/apollographql/apollo-client/pull/8699/files

In this change, arguments of `selectHttpOptionsAndBody` function also changed which is used in `createHttpLink`.
https://github.com/apollographql/apollo-client/pull/8699/files#diff-302faec6602520ccb4f8947dc7614daf1c40de0c264de8dbcd4104502ac3f5a0R116

We need to add `print` option to `selectHttpOptionsAndBody` through `createHttpLink` to get along with apollo-client  >= v3.5.0.

**Comment by jaydenseric** [comment]
[I originally intended](https://github.com/jaydenseric/apollo-upload-client/pull/274#issuecomment-967740091) to work on this issue last week, but the other project I wanted to finish first hit a few snags and I couldn't get it done before going on a pre-planned hiking trip in the bush over the weekend.

Apollo have acknowledged this issue is a due to a breaking change that they incorrectly published in an Apollo Client semver non-major release, and they have a PR that will fix the problem soon: https://github.com/apollographql/apollo-client/pull/9103 .

We will still add support for the new [`print`](https://www.apollographql.com/docs/react/api/link/apollo-link-http/#print) option here via https://github.com/jaydenseric/apollo-upload-client/pull/274, but it will be as a new feature instead of an urgent bug fix. That PR needs a bit more work (documentation of the new option, changelog entry, etc.) that I intend to do once we can base it on the coming Apollo Client patch release.

**Comment by jaydenseric** [comment]
Closing because this issue should be fixed in Apollo Client v3.5.5:

https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-355-2021-11-23

We can track adding support for the new [`print`](https://www.apollographql.com/docs/react/api/link/apollo-link-http/#print) option in another issue/PR.

**Comment by tm1000** [comment]
Thanks @jaydenseric !!
