### ISSUE TITLE
Network Error, using React native( without flipper ) 

### ISSUE THREAD

**Issue by hamdij0maa** [jaydenseric/apollo-upload-client#279]
I am getting : Network error with : isTrusted = false, while uploading a file to a laravel lighthouse backend.
only while using a slow internet.

**Comment by halberio** [comment]
+1

**Comment by hamdij0maa** [comment]
No response ? no recommendations ? looool

**Comment by mike-marcacci** [comment]
@hamdij0maa this isn't even close to actionable or useful. If you want somebody to drop what they're doing and spend their own very valuable time providing free help for your project, you might consider providing _some_ context before pestering them from your various accounts, on a major holiday no less.

This kind of entitlement is why people leave open source.

**Comment by hamdij0maa** [comment]
If you have something good to say, do it, or just keep calm ^^this is a common issue with this library.

**Comment by jaydenseric** [comment]
Closing because I can't see any evidence your problems have anything to do with this repo. React Native has all sorts of weird networking problems (particularly relating to multipart requests), and helping people debug their React Native projects is beyond the scope of the `Apollo-upload-client` project.

> No response ? no recommendations ? looool

@hamdij0maa rest assured, that when I get an email alert about an issue that my experience and intuition suggests it might be an actual bug in the published code, I drop everything and reply, problem solve and publish a fix with some of the fastest turn around times in the entire industry. If it happens in daylight hours, Melbourne Australia time, I often reply within 2 minutes.
