### ISSUE TITLE
cropping image before uploading

### ISSUE THREAD

**Issue by ablbol** [jaydenseric/apollo-upload-client#28]
Hi,
Thanks for this great library.  I have a question.  Is there a way to crop the image before uploading the image or should the image be cropped server side?  I noticed that the library deals with File or FileList objects but if I crop the image client side, I am not sure how to change back to File object. Please share any library to crop images server side.
Thanks

**Comment by jaydenseric** [comment]
Hmm. If you do the cropping client side you can export the canvas as a base64 string. You can use the string in a normal GraphQL request variable, and then use it to save an image on the server in the resolver.

To crop or otherwise manipulate images on the server, I suggest using [Sharp](https://github.com/lovell/sharp).

**Comment by jaydenseric** [comment]
If it makes sense to, we could add [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob) to the list of objects in [`extract-files`](https://github.com/jaydenseric/extract-files) considered files for upload to make uploading from canvas easier via [`toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob). I guess blobs would have to upload with no filename and potentially no mime type.

**Comment by n1ru4l** [comment]
@ablbol You can use the File constructor to create a File object from a
blob object (https://w3c.github.io/FileAPI/#file-constructor)

```javascript
const file = new File([blob], `image.jpeg`)
```


On Aug 8, 2017 8:33 AM, "Jayden Seric" <notifications@github.com> wrote:

If it makes sense to, we could add Blob
<https://developer.mozilla.org/en-US/docs/Web/API/Blob> to the list of
objects in extract-files <https://github.com/jaydenseric/extract-files>
considered files for upload to make uploading from canvas easier via toBlob
<https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob>.
I guess blobs would have to upload with no filename and potentially no mime
type.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jaydenseric/apollo-upload-client/issues/28#issuecomment-320863665>,
or mute the thread

**Comment by jaydenseric** [comment]
@n1ru4l nice.

Closing because the question is answered, but feel free to discuss more 🙂

**Comment by ablbol** [comment]
This is very helpful.  Thanks

**Comment by keeth** [comment]
I have the same problem, trying to upload cropped images.  I'm converting a data URI to a blob/file.

@n1ru4l's solution works in Chrome but doesn't appear to work in Webkit.  

It seems like passing a Blob to formData.append is required.

**Comment by smithaitufe** [comment]
Please is this to say that if you crop an image, in my case, react native, upload won't work? Because I am experiencing an issue that I have reported here https://github.com/jaydenseric/apollo-upload-client/issues/64

Please what do you think?

**Comment by Access2emma** [comment]
How can i resize the image on the server before saving to folder? I'll appreciate complete example too
