### ISSUE TITLE
Dynamic require of "@apollo/client/core" is not supported

### ISSUE THREAD

**Issue by dtillner** [jaydenseric/apollo-upload-client#280]
I using @apollo/client and apollo-upload-client with vite and vue. With the update from apollo-upload-client 16.0.0 to 17.0.0 I get the following error:

`Uncaught Error: Dynamic require of "@apollo/client/core" is not supported`

My imports are

```
import { ApolloClient, InMemoryCache } from '@apollo/client/core';
import { setContext } from "@apollo/client/link/context";
import { createUploadLink } from 'apollo-upload-client'
import VueApollo from 'vue-apollo';
```

I can't import only `@apollo/client` because it depends on react that I do not need.

**Comment by jaydenseric** [comment]
I can't see how whatever problem you're having could be due to changes in `apollo-upload-client` v12 -> v17; the `@apollo/client` related require paths are identical:

- https://unpkg.com/browse/apollo-upload-client@16.0.0/public/createUploadLink.js
- https://unpkg.com/browse/apollo-upload-client@17.0.0/public/createUploadLink.js

**Comment by dtillner** [comment]
Seems like it was a problem with vite.

My vite config included:

```
optimizeDeps: {
  include: ['@apollo/client/core', '@apollo/client/link/context'],
  exclude: ['@apollo/client']
},
rollupInputOptions: {
  external: ['react']
}
```

I hasd to change that to:

```
optimizeDeps: {
  include: ['@apollo/client/core', '@apollo/client/cache', '@apollo/client/link/context'],
  exclude: ['@apollo/react']
},
rollupInputOptions: {
  external: ['react']
}
```

Now everything works as intended.

Interesting is that the error only happened with `apollo-upload-client` v17...

**Comment by loremru** [comment]
Could anyone help with nuxt 3? I have the same error. But vite config doesn't help

**Comment by jmverges** [comment]
@loremru same here. @jaydenseric any clue?

**Comment by jaydenseric** [comment]
@jmverges it's related to the setup of your particular project and not something I can really help with.

**Comment by jmverges** [comment]
@jaydenseric could you confirm apollo-upload-client works with nuxt3 ?

**Comment by jaydenseric** [comment]
@jmverges no; I'm not a nuxt user. The burden is on frameworks and users of those frameworks to get typical packages like `apollo-upload-client` working, not the other way around.

**Comment by jmverges** [comment]
@jaydenseric sure thing. However is it normal the users comes to the package to see if other people is in the same situation. @dtillner are you using nuxt3? I tried your config but I got the same result when npm run dev and vite is in place.

**Comment by jmverges** [comment]
hi again @jaydenseric this fixed the issue for me: https://github.com/jmverges/apollo-upload-client/commit/5e09361ead8699c1385b1bbceeba4e02fbbd6db2 do you have any opinion or advice about it?

**Comment by jaydenseric** [comment]
@jmverges it seems you are using some kind of tooling that doesn't understand how to deal with Node.js packages. In Node.js, ESM modules can import CJS modules, e.g:

https://nodejs.org/dist/latest-v17.x/docs/api/packages.html#approach-1-use-an-es-module-wrapper

In the past I've seen Rollup based setups have problems with mixed ESM/CJS; they have been very late to the package `exports` and Node.js ESM/CJS interop party compared to other tools. Perhaps you have Rollup somewhere in your build tooling? I don't want to unfairly point fingers tho, and I haven't recently checked up on any recent improvements Rollup has made.

Note that I've been gradually working through every package I maintain, converting them to pure ESM in `.mjs` files with TypeScript v4.6.0-dev.x and Deno flavoured types via JSDoc comments. At some point `apollo-upload-client` will be converted accordingly. I'm doing this package later than other ones because I don't actually use it, so don't urgently need it to be pure ESM like some of the other things I'm using in pure ESM/Deno projects, and because the later the change is made the more time users have had a chance to get used to the emerging pure ESM future of the JS ecosystem. Apollo seems to have made progress on ESM compatibility, so hopefully it won't be too difficult to work with here when the time comes.

**Comment by jmverges** [comment]
Thanks @jaydenseric I brought back the mjs in the packages.json in the fork. I still don't get why "require" is giving me problems. However with "import" and "export" everything works well. 
I don't know what is a Rollup setup but I will be looking for it. I'm using nuxt3 with vite.

**Comment by winnysan** [comment]
@jmverges @loremru  hi, you found a solution to this problem with nuxt 3?

**Comment by datlc-1387** [comment]
I am using nuxt 3,  I have installed plugin `@originjs/vite-plugin-commonjs` for vite.

```typescript
import { esbuildCommonjs } from '@originjs/vite-plugin-commonjs';

export default defineNuxtConfig({
  vite: {
    optimizeDeps: {
      esbuildOptions: {
        plugins: [esbuildCommonjs(['apollo-upload-client'])],
      },
    },
  },
};
```

And it worked.
