### ISSUE TITLE
Cannot customize index/key name of upload.

### ISSUE THREAD

**Issue by ComputerCarl** [jaydenseric/apollo-upload-client#286]
The server I am using is requesting a `File` upload and a map of:
`{"attachment": ["variables.attachment"]}`

I have modified to input name in attempt to make it match the map, but still get `"1"`.
` {"1":["variables.attachment"]}`

The `apollo-upload-client` is a terminating link, so I believe I cannot modify the request.

How can I send the correct map?

References:
[Issue](https://github.com/jaydenseric/apollo-upload-client/issues/284): 
User tries to use;
`"map": { "theFile": ["variables.file"] }
"theFile":  <the file to upload>`

[Issue](https://github.com/jaydenseric/apollo-upload-client/issues/171): User wants to start key at `0` instead of `1`.
> According to the GraphQL multipart request spec, the file field names can be anything unique; they don't even have to be numbers

[graphql-multipart-request-spec ](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure):
Example shows first file starting at "0"

**Comment by jaydenseric** [comment]
As you rightly noted from past issue comments, the `map` field keys can be anything the client generates and a server should not have expectations about what they are. There are no plans to allow users to customise these in `apollo-upload-client`, so if you really can't fix the GraphQL API you might have to fork this package to get it to generate the specific keys you want.

It's a weird design for that GraphQL API server to specifically expect `attachment`; what happens when you have a mutation that accepts multiple uploads? Did they hardcode the server to only accept a single file, forever, or will they expect `attachment2`, `attachment3`, etc.

**Comment by raja-OX** [comment]
[apollo-upload-client.zip](https://github.com/jaydenseric/apollo-upload-client/files/12596820/apollo-upload-client.zip)

@ComputerCarl  Customized version with typescript by forking the package and changing it as you want.

@jaydenseric In createUploadLink.js change the ++i instead i++. Or else you can use the file I've attached.

```js

 const map = {};
      let i = 0;
      files.forEach((paths) => {
        map[i++] = paths;
      });

      form.append("map", JSON.stringify(map));

      i = 0;
      files.forEach((paths, file) => {
        const fileName = i++;
        customFormDataAppendFile(form, fileName?.toString(), file);
      });

```
