### ISSUE TITLE
FIle always null in apollo client

### ISSUE THREAD

**Issue by cavator** [jaydenseric/apollo-upload-client#289]
i follow this video [Youtube](https://www.youtube.com/watch?v=BcZ_ItGplfE)
and did the basic
![image](https://user-images.githubusercontent.com/14593967/162373907-f0539520-d4c1-4026-b4b9-51b0f6ad881b.png)
i think headers are right
![image](https://user-images.githubusercontent.com/14593967/162374132-4ce52a23-85cd-4484-bfa3-a1c5d24af1b2.png)
and in the request shows the contract is null, even showing it's sending the file in the payload
![image](https://user-images.githubusercontent.com/14593967/162374546-00693fbd-9048-4300-bdcc-f8f5a4346c75.png)
anyone know what I'm doing wrong? it's impossible upload file with another data together? i need do a endpoint just for upload a file?

**Comment by jaydenseric** [comment]
It's probably working ok; by design the original file value is replaced with `null` in the operation variables JSON (see https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure). The GraphQL server file upload middleware will put it back together on the other end.

Is the file upload working ok in your resolvers, is there a problem?
