### ISSUE TITLE
fetchOptions headers not working

### ISSUE THREAD

**Issue by Dreaming-Codes** [jaydenseric/apollo-upload-client#290]
Hi, I am trying to get my authentication system to work with this plugin but my headers are completely ignored.

My code:
```
            createUploadLink({uri: import.meta.env.VUE_API_URL + '/graphql', fetchOptions: {
                    headers: {
                        "Authorization": `Bearer ${localStorage.getItem("token")}`
                    }
                }})
```

Am I doing something wrong?

**Comment by jaydenseric** [comment]
Does it work if you move the `headers` one level up, directly in the link options? It's supposed to support both ways, with the higher level shortcut merging with and overriding a `headers` object deeper in `fetchOptions`, matching the normal Apollo HTTP link API:

https://github.com/jaydenseric/apollo-upload-client/blob/5dc76ca4c4ae2188a9bb3802b2aae9a58761ecba/public/createUploadLink.js#L45

Because Apollo has multiple ways to configure the same things (about 3 ways), it's a little tricky at first to understand the link implementation code. If there is a bug with the merging of options, it might be happening in this Apollo maintained code:

https://github.com/jaydenseric/apollo-upload-client/blob/5dc76ca4c4ae2188a9bb3802b2aae9a58761ecba/public/createUploadLink.js#L116
https://unpkg.com/@apollo/client@3.5.10/link/http/selectHttpOptionsAndBody.js

**Comment by Dreaming-Codes** [comment]
If I put it in headers file upload stops working.
I solved by creating a wrapper to the fetch function that authenticates the
request before sending it.

Il lun 11 apr 2022, 01:33 Jayden Seric ***@***.***> ha
scritto:

**Comment by jaydenseric** [comment]
If you are able to put together a *minimal* reproduction of the issue we can reopen (ideally a PR with a failing test case), but for now I'm guessing there is something strange about your specific project because if headers were not working properly thousands of people would have noticed by now.

Another thing to double check, is this in the readme installation instructions:

> Remove any `uri`, `credentials`, or `headers` options from the [`ApolloClient` constructor](https://apollographql.com/docs/react/api/core/ApolloClient/#the-apolloclient-constructor).
