### ISSUE TITLE
fetchOptions not work

### ISSUE THREAD

**Issue by MoGoethe** [jaydenseric/apollo-upload-client#295]
const uploadLink = createUploadLink({
  uri: '/api/graphql',
  credentials: 'include',
  fetchOptions: { signal: abortController.signal },
});

fetchOptions: { signal: abortController.signal } is not work when i catch error :

`Uncaught (in promise) DOMException: The user aborted a request.`

https://github.com/apollographql/apollo-client/issues/6769

**Comment by MoGoethe** [comment]
import { createHttpLink } from '@apollo/client';

const uploadLink = createHttpLink({
  uri: `/api/graphql`,
  credentials: 'include',
  fetchOptions: { signal: abortController.signal },
});


createHttpLink is work good

**Comment by jaydenseric** [comment]
We have tests for using `fetchOptions.signal`:

https://github.com/jaydenseric/apollo-upload-client/blob/234a72799616481e874d219e9edd9fc7b7993857/test/public/createUploadLink.test.mjs#L990-L1131

Can you try and see if it works with `@apollo/client` v3.5.10 in your project because that's likely the most recent version I ran the tests against: 

https://github.com/jaydenseric/apollo-upload-client/blob/234a72799616481e874d219e9edd9fc7b7993857/package.json#L54

**Comment by MoGoethe** [comment]
Thanks and i switched to v3.5.10 it worked fine. thanks !!!

**Comment by jaydenseric** [comment]
Maybe you should investigate what changed with `@apollo/client` and see if you need to report a bug in their repo.

**Comment by YoruNoHikage** [comment]
It seems to happen from v3.6.8 and above.
If you look at the diff https://github.com/apollographql/apollo-client/compare/v3.6.7...v3.6.8 it might be related to the removal of the `quietly` argument on observables. Is it a bug or does that mean something needs to be done here?
