### ISSUE TITLE
Unexpected token issue right after upload

### ISSUE THREAD

**Issue by GuillaumeBordeau** [jaydenseric/apollo-upload-client#299]
Hello,
the upload request return the following error :
`Error: Unexpected token 'W', "
Warning: C"... is not valid JSON`
the media is correctly created, but the request return that error.

Is this a known error or does anybody have already encountered something like this.

**Comment by NicoSan20** [comment]
@GuillaumeBordeau : I had the same issue.

For me, the issue was on the apollo server side. In the documentation, `*.use(graphqlUploadExpress())` is located between the `*.start()` and `*.applyMiddleware()`

Once `*.use(graphqlUploadExpress())` placed above `new ApolloServer()`, I no longer had this issue.

Hope this gives you some clue ;)

**Comment by jaydenseric** [comment]
Closing because a presumably correct explanation was given.
