### ISSUE TITLE
`Uncaught TypeError: Cannot read properties of undefined (reading 'call')` upon build project.

### ISSUE THREAD

**Issue by StefanusChristian** [jaydenseric/apollo-upload-client#311]
Hi, my team has develop upload feature in our project using `apollo-upload-client` and it works without problem. But when we build the project and run it, it only show blank white screen and gives console error:
```tsx
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
```

The error from my code was when I'm using the `createUploadLink`. Can confirm when replacing it with `createHttpLink` from `@apollo/client`, the build run as it should.

After further tracing it, it was caused by the `'@apollo/client/core'` require in `createUploadLink.js`. It might because of the `ApolloLink` or `Observable`.

<details>
<summary>Screenshots</summary>

<img width="1316" alt="Screen Shot 2023-07-06 at 5 50 26 PM" src="https://github.com/jaydenseric/apollo-upload-client/assets/25154563/c176e246-3ac0-4437-a72b-bfd48663f1ff">

<img width="1317" alt="Screen Shot 2023-07-06 at 6 08 09 PM" src="https://github.com/jaydenseric/apollo-upload-client/assets/25154563/f969bb9a-ed6d-4dd1-a909-5d8b44e06c8d">

</details>

<details>
<summary>Code snippet of createUploadLink usage</summary>

```tsx
const httpLink = createUploadLink({ // If change with createHttpLink, build will works
  uri: API_URL,
  credentials: 'same-origin',
});
const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query);

    return (
      definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
    );
  },
  wsLink,
  httpLink,
);

export const client = new ApolloClient({
  link: from([errorLink, authLink, splitLink]),
});
```
</details>

I'm developing my project using `react-native-web` and here's some of the library we use: 
- `"expo": "^47.0.0",`
- `@apollo/client: "^3.6.9"`
- `"graphql": "15.8.0"`
- `"react": "18.1.0"`
- `"react-dom": "18.1.0"`
- `"react-native": "0.70.5"`

**Comment by jaydenseric** [comment]
If you do this in a CJS module in your project, does it work?

```js
const { ApolloLink, Observable } = require("@apollo/client/core");
```

We need to figure out where the issue lies; with your project's build setup, with the `@apollo/client` package, or if it's something which needs to be fixed in `apollo-upload-client`.

The state of maintenance of this package is a bit in limbo because I want to work on and support the newer version currently in the `next` branch (see changes [here](https://github.com/jaydenseric/apollo-upload-client/blob/next/changelog.md#next)), but can't progress that work due to an upstream `@apollo/client` issue: 

https://github.com/apollographql/apollo-client/issues/9890

Although it's not closed yet, it looks like they might be making progress in the last couple of weeks:

https://github.com/apollographql/apollo-client/pull/10994

So I might resume work here when I next get some spare time.

**Comment by jaydenseric** [comment]
Closing due to no response, and also because it seems no other users are experiencing similar errors. If it turns out to be a bug here (and not a project or React Native related issue) we can reopen.
