### ISSUE TITLE
Is this library abandonded? 

### ISSUE THREAD

**Issue by erickarnis-tb** [jaydenseric/apollo-upload-client#315]
Latest release was Dec 7th 2021, latest push was Apr 24, 2022

**Comment by jaydenseric** [comment]
It's not abandoned; the status is that in July 2022 I was working on a bunch of updates that modernise the package in line with my other open source packages but ran into a problem with the `@apollo/client` dependency publishing modules and types that are invalid for TypeScript in `compilerOptions.module` mode of `nodenext`:

https://github.com/apollographql/apollo-client/issues/9890#issuecomment-1178389108

That's a blocker to the work I was doing here, and so pushed what I started to the branch [`next`](https://github.com/jaydenseric/apollo-upload-client/tree/next), and I've been tools down ever since waiting for Apollo to fix it. Over a year later they still haven't. As soon as it's fixed upstream, I'll do a bunch of maintenance here. In the meantime I still actively monitor and respond to issues raised.

I personally don't use anything Apollo in my personal and professional work these days, having published my own GraphQL server and client packages (e.g. [`graphql-api-koa`](https://github.com/jaydenseric/graphql-api-koa), [`graphql-react`](https://github.com/jaydenseric/graphql-react)). So I just maintain `apollo-upload-client` now as a favour to the community.

**Comment by erickarnis-tb** [comment]
Hi, thanks for the response. Good to know that the holdup is not on your end, sorry they have been so unresponsive.

**Comment by phryneas** [comment]
https://github.com/apollographql/apollo-client/issues/9890 has been fixed at the beginning of August with the Release of Apollo Client 3.8.

**Comment by phryneas** [comment]
@jaydenseric I had [asked you for feedback](https://github.com/apollographql/apollo-client/issues/9890#issuecomment-1604232362) in that issue, that's why I didn't close it immediately.
