### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by zamaniramin549** [jaydenseric/apollo-upload-client#336]
I have install the package and when I import it 
import { createUploadLink } from 'apollo-upload-client'; 
I get Module not found. bellow is what I get

Package path . is not exported from package /Volumes/Projects/projects/TripChiz-App/web-app/node_modules/apollo-upload-client (see exports field in /Volumes/Projects/projects/TripChiz-App/web-app/node_modules/apollo-upload-client/package.json)

**Comment by ksenia-fe** [comment]
Facing the same issue

**Comment by jaydenseric** [comment]
Because that is not the correct way to import the module; if you look in `node_modules/apollo-upload-client/` you will see what you are attempting doesn't exist.

The package's exports are documented here, along with an explanation how they are to be imported:

https://github.com/jaydenseric/apollo-upload-client/blob/v18.0.1/readme.md#exports

```js
import createUploadLink from "apollo-upload-client/createUploadLink.mjs";
```
