### ISSUE TITLE
Query on Compatibility with @apollo/client 3.9.0 and apollo-upload-client

### ISSUE THREAD

**Issue by giovannetti-eric** [jaydenseric/apollo-upload-client#341]
Hi,

I noticed that @apollo/client was recently updated to version 3.9.0. However, apollo-upload-client still lists its peer dependency as @apollo/client version 3.8.0. I understand the reasons for not automatically updating peer dependencies, as discussed in [this pull request](https://github.com/jaydenseric/apollo-upload-client/pull/201).

Before I update to @apollo/client 3.9.0, I wanted to check if there are any known compatibility issues with apollo-upload-client. Are there any potential risks or known problems with using these two versions together?

Thanks for your help.

**Comment by jaydenseric** [comment]
Hello, this is how the peer dependency is defined:

https://github.com/jaydenseric/apollo-upload-client/blob/5e6d5c17861fbd9e2d84c8517fc29d5321be4cfc/package.json#L48

`^3.8.0` also includes v3.9.0, because of the `^`. You can learn more about how "carrot ranges" work here:

https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

Assuming that Apollo didn't sneak any breaking changes into the `@apollo/client` v3.9.0 release, it should be backwards compatible with v3.8.0. If you do discover something breaks due to upgrading from v3.8 to v3.9, you should report it to Apollo as a bug.
