### ISSUE TITLE
Feature request: support error status code

### ISSUE THREAD

**Issue by leethree** [jaydenseric/apollo-upload-client#47]
`apollo-client-http` includes some useful data in their thrown errors, e.g. HTTP status code. It would be great if `apollo-upload-client` can support it as well.

See: https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#errors

**Comment by dbelchev** [comment]
@leethree, I agree with you.
Here there is one example:
Server response:
<img width="481" alt="screen shot 2018-02-01 at 9 59 44" src="https://user-images.githubusercontent.com/9073252/35667701-5b5709f8-0737-11e8-9d5a-f2fd30b9ab0f.png">

```
const errorLink = onError(({ networkError, graphQLErrors, response, operation }) => {
  Reactotron.log(response);
});
```
'apollo-link-http' error data log:
<img width="493" alt="screen shot 2018-02-01 at 10 00 02" src="https://user-images.githubusercontent.com/9073252/35667852-cdb2c398-0737-11e8-94d7-7acf3c3165f8.png">

'apollo-upload-client' error data log:
<img width="493" alt="screen shot 2018-02-01 at 10 02 14" src="https://user-images.githubusercontent.com/9073252/35667875-e5010028-0737-11e8-8be5-1ab03ccc8245.png">

**Comment by Fi1osof** [comment]
@jaydenseric 
I just did this https://github.com/jaydenseric/apollo-upload-client/compare/master...Fi1osof:patch-1 and it`s make me happy (i can catch graphql errors);
But i think may be use getContext() is better way;

**Comment by jaydenseric** [comment]
Would someone like to verify this works as expected with [`apollo-upload-client@7.1.0-alpha.1`](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v7.1.0-alpha.1)?

**Comment by dbelchev** [comment]
Hey, @jaydenseric!

Thank you! I would love to do it!

**Comment by dbelchev** [comment]
Hey @jaydenseric,

The COOL part:
I can confirm that  apollo-upload-client@7.1.0-alpha.1 returns the same data for networkError and graphQLErrors as THE CURRENT VERSION of apollo-link-http. 👍

The (somehow) weird part:
This issue was about the additional request response data, which THE ERLIER VERSION OF apollo-link-http used to return. Today I was somehow surprised to find out that the current version of apollo-link-http no longer returns the *response* prop as part of the network error with the actual http request status code (not only the graphQLError code).

For the results from the earlier version of apollo-link-http you can refer to my previous post [here](https://github.com/jaydenseric/apollo-upload-client/issues/47#issuecomment-362189258)

For the current results of the already consistent error result of apollo-link-http and apollo-upload-client you can check the following screenshot:

The log from the bottom to the top:
1. errorLink error.response (undefined)
2. errorLink error.graphQLErrors
3. errorLink error.networkError

<img width="542" alt="screen shot 2018-02-16 at 15 16 04" src="https://user-images.githubusercontent.com/9073252/36317323-76b0e8c6-1345-11e8-8441-2b41036b25bd.png">

Anyway, I think that the current state provides more than enough information, since in case of 4** status there will be not only graphQLError object, but networkError object as well, with the additional graphQLError data and code (unlike the previous version).

Cheers!
