### ISSUE TITLE
Filesize

### ISSUE THREAD

**Issue by hoodsy** [jaydenseric/apollo-upload-client#55]
Considering we have the file's size in the browser, it would be pretty convenient to have `size` on the server as well.

Uploading to say s3 requires the filesize, so this would be quite nice.

**Comment by jaydenseric** [comment]
There are 2 ways this could be implemented…

1. Naively trust the client, and have the client send the file size. I don't intend to incorporate this approach because developers will inevitably end up trusting it in the resolvers when doing validation, etc.
2. Measure the actual size of the upload as it streams into the server. You only know the total size once the upload stream finishes. This is how packages such as `formidable` (previously used in `apollo-upload-server`, prior to the streams rewrite) report file sizes.

There are packages available that you can use to pull metadata from a file stream; some metadata can be derived without having to parse the entire file, others are only available once the stream is done. I have not had to do this myself yet, so I can't recommend specific packages. If you settle on this approach, let us know your recommendations 🤓

[Here](https://github.com/jaydenseric/apollo-upload-client/issues/52#issuecomment-355808793) is a somewhat related comment.

Are you sure S3 requires the file size beforehand to upload? I tried reading the docs and could not see any mention. You should be able to pass the upload stream straight into their API (if you don't need to do any local validation first).

**Comment by hoodsy** [comment]
Oh! You're right, it isn't required! This saves some hassle... also, thank
you for the insights into potential approaches.

I probably won't invest extra time to parse the filesize, but if I do, I'll
let you know what I landed on. :D

**Comment by jaydenseric** [comment]
Awesome 😅
