### ISSUE TITLE
Client is sending null in the query

### ISSUE THREAD

**Issue by FahdW** [jaydenseric/apollo-upload-client#59]
My query payload which contains the file portion of the mutation is now sending null when i send the payload to my backend.

```    const file = {
      file: acceptedFiles[0],
      type: 'OTHER',
    };
    const documents = [file];

 uploadOrderDocument({
      orderId,
      documents: [documents],
    }).then(res => console.log(res))
      .catch(err => console.log(err));

**Comment by jaydenseric** [comment]
Are you using the latest versions of `apollo-upload-client`, and `apollo-upload-server`? They are using a newer version of the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec).

**Comment by levvsha** [comment]
@jaydenseric Is it possible to specify the value that will replace files instead of `null`? Our backend is built in such a way that it produces an error if it gets an array with `null` values.

**Comment by crirus** [comment]
I'm on the same boat with this, I can even accept a 'true', '1',  etc, or the actual file names instead null

**Comment by jaydenseric** [comment]
I'm not sure what you guys are explaining, because [`upollo-upload-server`](https://github.com/jaydenseric/apollo-upload-server) processes the request for you so your resolvers don't see any `null` values; they get [Upload scalars](https://github.com/jaydenseric/apollo-upload-server#upload-scalar) with `stream`, `filename`, etc.

**Comment by crirus** [comment]
I am not using apolo-upload-server, just the client and my implementation is standard graphql that rejects queries with fields set to null :)

**Comment by jaydenseric** [comment]
@crirus You need a server implementation for the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec#server) running before your GraphQL server or nothing will work properly.

**Comment by crirus** [comment]
@jaydenseric I know, we already handle your operations and maps POST keys, but inside the input query, all fields about files are set to null, hence the query is invalidated before we get control of execution in resolvers.

We could convert that input query to change the nulls, but it could be more elegant if your client send some acceptable, useful values instead.

Regards
Cristian

**Comment by jaydenseric** [comment]
@FahdW We can reopen this if you decide to answer [my earlier question about what versions you are using](https://github.com/jaydenseric/apollo-upload-client/issues/59#issuecomment-361033566) and clarify the problem. I can't understand what your issue with `apollo-upload-client` actually is; the code excerpt does not have any context and does not look like a typical use of the Apollo Client API. It's also confusing what you mean by the client sending `null` in place of the files, since in a way that is what is meant to happen.

@crirus It seems you are trying to build a custom server implementation of the spec and are finding it challenging. The right place to discuss that is the [`#uploads` chanel of the Apollo Slack](https://apollographql.slack.com/messages/uploads) where I would be happy to help.

**Comment by crirus** [comment]
it's not a custom built, it's using facebook graphql protocol. Simply, if yous end a field with null, it's not accepted. Even 0 is fine.

**Comment by jaydenseric** [comment]
@crirus see https://github.com/jaydenseric/graphql-multipart-request-spec/issues/4#issuecomment-351622279.

I think you are confused about how this ecosystem fits together.

**Comment by crirus** [comment]
I am not, neither you are: basically you use null, graphql is not accepting it. I don't know why is a problem (if is a problem) to put anything there but null. :)

**Comment by jaydenseric** [comment]
Your GraphQL server should never receive a null value, because you should have middleware that decodes the multipart request according to the spec, and creates the standard input the GraphQL server expects to consume later in the middleware chain.

I'm guessing that because you have not setup `apollo-upload-server` as per the instructions, you must have a non-Node.js environment. There are [other server implementations for PHP and Ruby](https://github.com/jaydenseric/graphql-multipart-request-spec#server) you can try.

**Comment by crirus** [comment]
I know, exactly this is happening, we have a middleware to deal with this special POST format, we also replace those nulls, but we could avoid looping through all the queries, if client would send something else.

**Comment by FahdW** [comment]
@jaydenseric you can close this issue I managed to fix my issue.

**Comment by FahdW** [comment]
@jaydenseric I recently updated, both my Apollo server and client for my upload stuff. I now get an error when trying to upload, when it previously worked. Get an error like `TypeError: path must be a string or Buffer
    at Object.fs.unlink (fs.js:1055:11)
    at paths.forEach.path (/Users/fwahab/Development/notary-api/node_modules/@rmtech/internal-services-client/lib/document.js:58:24)
    at Array.forEach (<anonymous>)
    at DocumentApi.upload (/Users/fwahab/Development/notary-api/node_modules/@rmtech/internal-services-client/lib/document.js:57:15)
    at uploadOrderDocumentsMutation (/Users/fwahab/Development/notary-api/src/schema/document.js:54:59)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
