### ISSUE TITLE
connection resets in chrome

### ISSUE THREAD

**Issue by OneCyrus** [jaydenseric/apollo-upload-client#60]
there's a strange issue i can't really find the cause. i've implemented it very similiar to your example and it works quite well on edge and firefox. but in chrome i get ```POST http://localhost:8080/graphql net::ERR_CONNECTION_RESET```. usually i would say this is a server side issue. but even in wireshark i can see that the response is coming back to chrome and in firefox and edge it's working.

currently i'm trying with 7.0.0-alpha.3. any ideas?

**Comment by jaydenseric** [comment]
Hmm, that's strange; I can't think of anything obvious.

**Comment by jaydenseric** [comment]
Any news? [Apollo Client devtools](https://github.com/apollographql/apollo-client-devtools) can cause wierd issues sometimes; if you have it running that might explain why only Chrome has problems. You could try disabling it and see if it helps.

**Comment by OneCyrus** [comment]
no, couldn't find the root cause yet. even starting chrome with a new userdatadir and  disabled CORS it has this issue. (so not extension related)

a really strange issue...

**Comment by jaydenseric** [comment]
Googling around, there are a lots of things that can cause this in Chrome. Clearing cookies, disabling VPN, reinstall Chrome, etc. have all been known to help. From memory, there was a certain Node.js version that came out last year that had a bug that caused a similar issue with Next.js/Webpack and HMR. It has since been patched in all those projects.

Are you sure it is an issue with `apollo-upload-client`? Does it still happen when making queries with the regular http link? If so, does `apollo-upload-server` cause the issue? Are you are using the very latest version of `apollo-upload-server`?  Does it still error if you remove the server middleware?

I will reopen if you can confirm the error only occurs due to this package and provide clear steps to reproduce the issue; making a fix actionable 🙏

**Comment by iaheck** [comment]
Hello, I'm having this same issue. It works well in Safari but in Chrome it instantly returns `POST http://localhost:3000/graphql net::ERR_CONNECTION_RESET` on the console, and the app says `ApolloError: Failed to fetch`. It's not related to the server, because it fails on the same way in Chrome even when I shut down my server (in Safari it gives error 500 in that case, which makes sense)
Our client was working fine with regular http link and mutations works well even when we replaced that with createUploadLink. But the particular mutation that tries to upload a file it's not called from Chrome. Do you have an idea of what could this be? thanks in advance!

**Comment by jaydenseric** [comment]
@iaheck try it in Chrome in incognito mode, without any Chrome extensions enabled. Changes are there is some sort of developer tooling related to requests that might be interfering. In the past, tools for inspecting network traffic have caused problems (particularly React Native tooling).

**Comment by iaheck** [comment]
Thanks for the reply! It gave me the same error though. The error appears on `createUploadLink.js` at line 208

**Comment by iaheck** [comment]
hey @jaydenseric, we resolved the error! we were using a custom URI as [described here](https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink) but we needed to append an `/` at the end of the URI. Safari added that extra `/` but Chrome did not so that was the reason of the error.

Maybe we could add that to the documentation, thanks for your help!

**Comment by jaydenseric** [comment]
@iaheck interesting, glad you solved the mystery :)
