### ISSUE TITLE
Support creating a custom FormData object.

### ISSUE THREAD

**Issue by dbelchev** [jaydenseric/apollo-upload-client#67]
Is it possible to provide additional prop to the link config options, to support custom FormData handling, e.g.

```
customFormData: (query, fetchOptions, files) => {
const body = new FormData();
...balblalbalb...

return body;
}
```

This will allow more versatility, because not always back-end refactoring to support a certain request convention is an option.

Thank you!

**Comment by jaydenseric** [comment]
> back-end refactoring to support a certain request convention

Not really sure what you mean by this, either a multipart request is [spec valid](https://tools.ietf.org/html/rfc7578) or it is not. The global `FormData` class in all browsers generates correct forms.

Are you able to explain some more details about your specific use case?

**Comment by jaydenseric** [comment]
This library orientates around the [multipart GraphQL request spec](https://github.com/jaydenseric/graphql-multipart-request-spec), which is versatile and has a variety of server [implementations](https://github.com/jaydenseric/graphql-multipart-request-spec#implementations) in multiple languages.

I really strongly believe the community needs to rally around a single spec for transporting uploads, so that any client and server will be compatible. If you really want to implement a different approach, you can use the [`extract-files`](https://www.npmjs.com/package/extract-files) and [`apollo-link-http-common`](https://www.npmjs.com/package/apollo-link-http-common) packages to make a custom network interface 🙂
