### ISSUE TITLE
Network error: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by benhjames** [jaydenseric/apollo-upload-client#8]
On upgrading from 3.0.3 to 4.0.0 I get the following error:

```
Network error: Cannot read property 'headers' of undefined
  at new ApolloError ([...]/node_modules/apollo-client/apollo.umd.js:1851:28)
```

I think it should be passing `options` through to `window.fetch` as well as `opts`?

**Comment by jaydenseric** [comment]
@AdamYee ?

Just tried updating [apollo-upload-examples](https://github.com/jaydenseric/apollo-upload-examples) to v4 and it immediately errors.

**Comment by jaydenseric** [comment]
I think [this](https://github.com/jaydenseric/apollo-upload-client/pull/7/files#diff-5c3ea929867e47441d0adf8c7b240d9bR31) and [this](https://github.com/jaydenseric/apollo-upload-client/pull/7/files#diff-dd02b3429f244bcef288fc3fa836abccR43) should not have been changed.

**Comment by AdamYee** [comment]
Hey guys,

I was able to reproduce by removing `opts` from the `createNetworkInterface` config. Something that I didn't test because my app needs the cookies. Fetch queries (not mutations) will just fail silently, but when I attempt to upload a file I get the same error as @benhjames.

@jaydenseric so the changes to the lines you referenced are still needed, but they need to pass in an empty object when there isn't an `opts` defined when creating the network interface like what most people probably do at first:
```javascript
const networkInterface = createNetworkInterface({
  uri: '/graphql'
});
```

The fix should look something like this in the network-interface.js and batch-network-interface.js files:
```javascript
return _HTTPFetchNetworkInte.prototype.fetchFromRemoteEndpoint.call(this, { request: request, options: options.opts || {} });
```

In the meantime, if people need a quick workaround they can create the network interface with an empty `opts`:
```javascript
const networkInterface = createNetworkInterface({
  uri: '/graphql',
  opts: {} // just to get around the 4.0.0 bug
});
```

😃

**Comment by jaydenseric** [comment]
This seems to be ok now on `master` branch.

I am getting paranoid every time I publish a new release, it's so hard to manually test everything. We really need some unit tests!

**Comment by jaydenseric** [comment]
Just released [v4.0.1](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v4.0.1), please let me know if everything is happy chappy 🙏

**Comment by AdamYee** [comment]
@jaydenseric updated to 4.0.1 and all is well.

**Comment by benhjames** [comment]
Yep, thanks a lot!
